version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: web_backend
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/docs/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
volumes:
  static:
  media:
  db:
  redoc:
