# Generated by Django 4.1.9 on 2023-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("#D2691E", "Chocolate"),
                    ("#008000", "Green"),
                    ("#00FFFF", "Aqua"),
                ],
                default="#D2691E",
                help_text="Выбрать цвет",
                max_length=66,
                unique=True,
                verbose_name="Цвета в HEX-color",
            ),
        ),
    ]
